# GitHub Actions workflow to build and deploy ASP.NET Core Web API to Azure
# This workflow uses OIDC for Azure authentication and deploys to the 'dev' environment

name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Docker build
        run: docker build -t ${{ github.repository }}:${{ github.sha }} .

      - name: Deploy infrastructure (placeholder)
        run: echo "Add az deployment group create here if you have Bicep/ARM files."

      - name: Azure Container Registry Login (placeholder)
        run: echo "Add az acr login here if using ACR."

      - name: Push Docker image to ACR (placeholder)
        run: echo "Add docker push here if using ACR."

      - name: Deploy to Azure App Service (placeholder)
        run: echo "Add az webapp deploy here if using App Service."
